apiVersion: apps/v1
kind: Deployment
metadata:
  name: Information
  labels:
    app: Information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Information
  template:
    metadata:
      labels:
        app: Information
    spec:
      containers:
        - name: Information
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-information
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/myOrders'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/myOrders'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
